[build]
  # 빌드 명령을 실행할 기본 폴더를 지정합니다.
  base = "client" 
  
  # 해당 폴더 안에서 실행할 명령어입니다.
  command = "pnpm install && pnpm run build"
  
  # base 경로(client)를 기준으로 한 출력 폴더입니다.
  publish = "dist" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200