[build]
  # 빌드 명령어를 실행할 기본 폴더입니다.
  base = "client"
  
  # 'client' 폴더 안에서 실행될 명령어입니다.
  command = "pnpm install && pnpm run build"
  
  # base(client) 폴더를 기준으로 생성된 결과물 폴더입니다.
  # 올려주신 이미지상 결과물은 client/dist에 생기므로 "dist"라고 적습니다.
  publish = "dist"

[[redirects]]
  # SPA(Single Page Application) 라우팅 지원
  from = "/*"
  to = "/index.html"
  status = 200